import ProductService from '../../src/services/product.service'
import { Clothing, Electronic, IProduct } from '../../src/models/product.model'

describe('ProductService', () => {
  describe('createProduct', () => {
    it('should not throw an error for valid product type', async () => {
      // Arrange
      const type = 'Electronic'
      const payload: IProduct = {
        product_name: 'Sample Electronic Product',
        product_thumb: 'http://example.com/product.jpg',
        product_description: 'This is a sample electronic product',
        product_price: 199.99,
        product_quantity: 20,
        product_shop: 'Sample Electronic Shop',
        product_attributes: {
          brand: 'Sample Electronic Brand',
          model: 'Model X',
          color: 123456
        },
        // product_id and timestamps are usually generated by the database
      }

      const result = await ProductService.createProduct(type, payload)

      expect(result.acknowledged).toBe(true)
    })
  })
})
